#!/usr/bin/env python3

import os
import sys

# Check if the files can be removed if cached not specified
def check_can_be_rm(working_file_diff, repository_diff, file):
    if working_file_diff and repository_diff:
        print(f"git-rm: error: '{file}' in index is different to both the working file and the repository", file=sys.stderr)
        sys.exit(1)
    elif working_file_diff and not repository_diff:
        print(f"git-rm: error: '{file}' in the repository is different to the working file", file=sys.stderr)
        sys.exit(1)
    elif repository_diff and not working_file_diff:
        print(f"git-rm: error: '{file}' has staged changes in the index", file=sys.stderr)
        sys.exit(1)

# Determine files to remove
def get_files_to_rm(files, index_dir, force, commits_dir, cached):
    files_to_remove = []
    for file in files:
        working_file_diff = False
        repository_diff = False

        index_file = os.path.join(index_dir, file)
        work_file = file
        
        # Check if file exists in index
        if not os.path.exists(index_file):
            print(f"git-rm: error: '{file}' is not in the git repository", file=sys.stderr)
            sys.exit(1)
        
        # Check if index file is same as working file      
        with open(work_file, 'r') as f1, open(index_file, 'r') as f2:
            if f1.read() != f2.read() and not force:
                working_file_diff = True
        
        # Check if commits dir exists
        if not os.path.exists(commits_dir) and not force:
            print(f"git-rm: error: '{file}' has staged changes in the index", file=sys.stderr)
            sys.exit(1)

        # Check if index file is same as commits file       
        latest_commit = len(os.listdir(commits_dir)) - 1
        commits_file = os.path.join(commits_dir, str(latest_commit), file)
            
        if not force:
            if not os.path.exists(commits_file):
                repository_diff = True
            else:
                with open(commits_file, 'r') as f1, open(index_file, 'r') as f2:
                    if f1.read() != f2.read():
                        repository_diff = True

        if not cached:
            check_can_be_rm(working_file_diff, repository_diff, file)
        else:
            if working_file_diff and repository_diff:
                print(f"git-rm: error: '{file}' in index is different to both the working file and the repository", file=sys.stderr)
                sys.exit(1)

        files_to_remove.append(index_file)
        
        # Remove from working directory if not --cached
        if not cached:
            if os.path.exists(work_file):
                files_to_remove.append(work_file)
            else:
                print(f"git-rm: error: '{file}' does not exist", file=sys.stderr)
                sys.exit(1)
    return files_to_remove


def main():
    # Checking valid arguments
    if len(sys.argv) == 1:
        print("usage: git-rm [--force] [--cached] <filenames>", file=sys.stderr)
        sys.exit(1)

    force = False
    cached = False
    files = []

    # Determining if force and/or cached 
    # Fine as files must start with alphanumeric, as mentioned in the spec
    for arg in sys.argv[1:]:
        if arg == "--force":
            force = True
        elif arg == "--cached":
            cached = True
        else:
            files.append(arg)

    if not files:
        print("usage: git-rm [--force] [--cached] <filenames>", file=sys.stderr)
        sys.exit(1)

    git_dir = '.git'
    index_dir = os.path.join(git_dir, 'index')
    commits_dir = os.path.join(git_dir, 'commits')

    # Check if .git directory exists
    if not os.path.exists(git_dir):
        print("git-rm: error: git repository directory .git not found", file=sys.stderr)
        sys.exit(1)

    files_to_remove = get_files_to_rm(files, index_dir, force, commits_dir, cached)

    # Remove files
    for file in files_to_remove:
        os.remove(file)

if __name__ == "__main__":
    main()